/* SPDX-FileCopyrightText: 2020-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

import com.vanniktech.maven.publish.GradlePlugin
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SourcesJar
import com.vanniktech.maven.publish.DeploymentValidation

plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id "com.vanniktech.maven.publish" version "0.36.0"
}

repositories {
  mavenLocal()
  mavenCentral()
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots'
  }
}

version = "1.5.3-SNAPSHOT"
group = "net.emustudio"

dependencies {
    implementation 'net.emustudio:edigen:1.5.3-SNAPSHOT'
}

gradlePlugin {
    plugins {
        edigenPlugin {
            id = 'net.emustudio.edigen-plugin'
            implementationClass = 'net.emustudio.edigen.plugin.EdigenPlugin'
            displayName = 'Edigen Gradle Plugin'
            description = 'Generates instruction decoder/disassembler of an emuStudio CPU plugin using Edigen.'
        }
    }
}

mavenPublishing {
  coordinates("net.emustudio", "edigen-gradle-plugin", version)
  configure(new GradlePlugin(
          new JavadocJar.Javadoc(),
          new SourcesJar.Sources()
  ))

  signAllPublications()
  publishToMavenCentral(true, DeploymentValidation.PUBLISHED)

  pom {
    name = 'Edigen Gradle Plugin'
    description = 'Generates instruction decoder/disassembler of an emuStudio CPU plugin using Edigen.'
    url = 'https://github.com/emustudio/edigen-gradle-plugin'
    licenses {
      license {
        name = 'GNU General Public License, Version 3.0'
        url = 'https://www.gnu.org/licenses/gpl-3.0.txt'
      }
    }
    developers {
      developer {
        id = 'vbmacher'
        name = 'Peter Jakubčo'
        email = 'pjakubco@gmail.com'
      }
    }
    scm {
      connection = 'scm:git:git@github.com:emustudio/edigen-gradle-plugin.git'
      developerConnection = 'scm:git:git@github.com:emustudio/edigen-gradle-plugin.git'
      url = 'https://github.com/emustudio/edigen-gradle-plugin'
    }
  }
}

signing {
  required {
    project.gradle.taskGraph.hasTask("publish")
  }

  def signingKey = findProperty("GPG_KEY") ?: System.getenv("GPG_KEY")
  def signingPassword = findProperty("GPG_PASSWORD") ?: System.getenv("GPG_PASSWORD")
  useInMemoryPgpKeys(signingKey, signingPassword)
}
